# -*- coding: utf-8 -*-
"""Cópia de atividade4_rag_pdf_api.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SYobOh0f-Z8m3rZn2KlR3Qfwe1aj0NLO

# Jarvis Trabalho de IA
Vamo usar esse aqui feito pelo professor pra gente já ter uma ideia, já ta tudo implementado aqui, pdf pra .md, chunking, indexações, embeddings, recupera texto, tem resposta e já integra com o telegram pra gente ter uma ideia de como funciona, depois a gente muda pra fazer num site sei lá com uma interface igual de uma LLM qualquer.

Nesta atividade você vai construir um pipeline RAG **de ponta a ponta** usando um arquivo PDF real como base de conhecimento.

## O que você vai aprender
1. **Converter PDF → Markdown** com a biblioteca Docling
2. **Fazer chunking** (divisão em trechos) de diferentes formas
3. **Indexar** os chunks com BM25, Embeddings (FAISS) ou Híbrido
4. **Recuperar** trechos relevantes para uma pergunta
5. **Gerar resposta** usando um LLM (flan-t5-small, igual à atividade anterior)
6. **Integrar ao Telegram** para conversar com o seu RAG pelo celular

---

## Visão Geral do Pipeline

```
PDF
 │
 ▼
[ETAPA 1] Docling → Markdown (.md)
 │
 ▼
[ETAPA 2] Chunking  →  lista de trechos de texto
 │
 ▼
[ETAPA 3] Indexação  →  BM25  |  FAISS  |  Híbrido
 │
 ▼
[ETAPA 4] Retrieval  →  top-k trechos relevantes
 │
 ▼
[ETAPA 5] Geração LLM  →  resposta em texto
 │
 ▼
[ETAPA 6] Bot Telegram  →  interface de chat
```

---
## ETAPA 0 — Instalação de dependências

Execute esta célula **uma vez** no início da sessão do Colab.
"""

# Docling: converte PDF em Markdown de forma estruturada
# rank_bm25: busca lexical
# sentence-transformers: embeddings semânticos
# faiss-cpu: índice vetorial
# transformers + accelerate: LLM (Qwen2.5-7B-Instruct)
# python-telegram-bot: bot do Telegram
# nest_asyncio: permite rodar o bot dentro do event loop do Colab/Jupyter


"""---
## ETAPA 1 — Carregar PDF e converter para Markdown com Docling

### Por que converter para Markdown?
PDFs são difíceis de processar diretamente: o texto pode estar fora de ordem, tabelas viram bagunça e figuras não têm texto.  
O **Docling** analisa a estrutura do PDF (títulos, parágrafos, tabelas, listas) e gera um Markdown limpo e organizado.

### Qual PDF usar?
Você pode usar qualquer PDF. Algumas sugestões:
- Um artigo científico da sua área
- O edital de um concurso público
- O regulamento de algum curso
- Uma apostila ou material de aula

> **Dica para o Colab:** faça upload do PDF em *Arquivo → Fazer upload para a sessão* ou monte o Google Drive.
"""

# Opção A — Upload direto no Colab
from google.colab import files

print("Selecione o PDF na janela que vai abrir...")
uploaded = files.upload()          # abre o seletor de arquivo
CAMINHO_PDF = list(uploaded.keys())[0]
print(f"Arquivo carregado: {CAMINHO_PDF}")

# Opção B — Usar o Google Drive (descomente se preferir)
# from google.colab import drive
# drive.mount('/content/drive')
# CAMINHO_PDF = "/content/drive/MyDrive/meu_arquivo.pdf"   # ajuste o caminho

#!pip -q install -U docling transformers sentence-transformers

# ── Conversão PDF → Markdown ──────────────────────────────────────────────────
from docling.document_converter import DocumentConverter

print("Convertendo PDF para Markdown...")
converter = DocumentConverter()
resultado = converter.convert(CAMINHO_PDF)

# O Docling retorna um objeto 'DoclingDocument'.
# O método export_to_markdown() entrega o texto estruturado.
texto_markdown = resultado.document.export_to_markdown()

# Salva o Markdown gerado para inspeção
# Usamos Path.with_suffix() para funcionar com qualquer extensão (.pdf, .PDF, etc.)
caminho_md = str(Path(CAMINHO_PDF).with_suffix(".md"))
Path(caminho_md).write_text(texto_markdown, encoding="utf-8")

print(f"Markdown salvo em: {caminho_md}")
print(f"Total de caracteres: {len(texto_markdown):,}")
print()
print("═" * 60)
print("PRÉVIA DOS PRIMEIROS 1000 CARACTERES:")
print("═" * 60)
print(texto_markdown[:1000])



"""---
## ETAPA 2 — Chunking: dividir o texto em trechos

### Por que fazer chunking?
LLMs e retrieval funcionam melhor com trechos **curtos e coesos** do que com documentos inteiros.  
Trechos muito curtos perdem contexto; trechos muito longos "diluem" a informação relevante.

Vamos implementar **três estratégias** diferentes:

| Estratégia | Ideia | Quando usar |
|---|---|---|
| **Por tamanho fixo** | Divide a cada N caracteres | Simples, baseline |
| **Por janela deslizante** | Cada chunk "avança" alguns caracteres, com sobreposição | Evita cortar ideias no meio |
| **Por parágrafos** | Usa as quebras de linha do Markdown como separador natural | Preserva estrutura do documento |
"""

# ── Estratégia 1: chunk de tamanho fixo ──────────────────────────────────────
def chunking_fixo(texto, tamanho=500):
    """
    Divide o texto a cada 'tamanho' caracteres.
    Simples e rápido, mas pode cortar frases no meio.
    """
    chunks = []
    inicio = 0
    while inicio < len(texto):
        fim = inicio + tamanho
        chunks.append(texto[inicio:fim])
        inicio = fim
    return chunks


# ── Estratégia 2: janela deslizante ──────────────────────────────────────────
def chunking_janela(texto, tamanho=500, sobreposicao=100):
    """
    Igual ao fixo, mas cada chunk avança (tamanho - sobreposicao) caracteres.
    A sobreposição garante que ideias no limite entre chunks não se percam.

    Atenção: sobreposicao deve ser MENOR que tamanho, senão o loop não avança.
    """
    if sobreposicao >= tamanho:
        raise ValueError(
            f"sobreposicao ({sobreposicao}) deve ser menor que tamanho ({tamanho})"
        )
    chunks = []
    passo = tamanho - sobreposicao
    inicio = 0
    while inicio < len(texto):
        fim = inicio + tamanho
        chunks.append(texto[inicio:fim])
        inicio += passo
    return chunks


# ── Estratégia 3: por parágrafos ─────────────────────────────────────────────
def chunking_paragrafo(texto, min_chars=100):
    """
    Usa as quebras duplas de linha (\n\n) como separadores naturais.
    Remove parágrafos muito curtos (menos que min_chars caracteres).
    """
    paragrafos = [p.strip() for p in texto.split("\n\n")]
    return [p for p in paragrafos if len(p) >= min_chars]


# ── Escolha a estratégia aqui ─────────────────────────────────────────────────
# Experimente trocar e observe como o número e tamanho dos chunks muda!
ESTRATEGIA = "paragrafo"    # opções: "fixo", "janela", "paragrafo"
TAMANHO_CHUNK = 1000         # usado em "fixo" e "janela"
SOBREPOSICAO = 100          # usado em "janela" (deve ser < TAMANHO_CHUNK)

if ESTRATEGIA == "fixo":
    chunks_brutos = chunking_fixo(texto_markdown, tamanho=TAMANHO_CHUNK)
elif ESTRATEGIA == "janela":
    chunks_brutos = chunking_janela(texto_markdown, tamanho=TAMANHO_CHUNK, sobreposicao=SOBREPOSICAO)
else:
    chunks_brutos = chunking_paragrafo(texto_markdown)

# Filtra chunks vazios primeiro, depois numera — garante IDs sequenciais sem lacunas
chunks_filtrados = [c.strip() for c in chunks_brutos if c.strip()]
chunks = [
    {"id": f"chunk_{i:04d}", "texto": texto}
    for i, texto in enumerate(chunks_filtrados)
]

print(f"Estratégia: {ESTRATEGIA}")
print(f"Total de chunks: {len(chunks)}")
print()
print("── Exemplo: chunk_0000 ──")
print(chunks[0]["texto"])
print()
print("── Exemplo: chunk_0001 ──")
print(chunks[1]["texto"] if len(chunks) > 1 else "(só 1 chunk)")

# ── Estatísticas dos chunks ────────────────────────────────────────────────────
tamanhos = [len(c["texto"]) for c in chunks]

print("Distribuição de tamanhos dos chunks (em caracteres):")
print(f"  Mínimo  : {min(tamanhos)}")
print(f"  Máximo  : {max(tamanhos)}")
print(f"  Média   : {np.mean(tamanhos):.0f}")
print(f"  Mediana : {np.median(tamanhos):.0f}")
print()
print("Quantiles:")
for q in [25, 50, 75, 95]:
    print(f"  {q}% dos chunks têm menos de {np.percentile(tamanhos, q):.0f} chars")

"""### 🔎 Reflexão — Experimente as três estratégias

Troque o valor de `ESTRATEGIA` para `"fixo"`, `"janela"` e `"paragrafo"` e reexecute as células.  
Anote na tabela abaixo:

| Estratégia | Total chunks | Média chars/chunk | Observação |
|---|---|---|---|
| fixo | ? | ? | |
| janela | ? | ? | |
| paragrafo | ? | ? | |

Qual estratégia produziu chunks mais "coerentes" para o seu documento?

---
## ETAPA 3 — Indexação

Agora vamos construir os índices de busca.  
Você já viu BM25 e FAISS na Atividade 3 — aqui a diferença é que trabalhamos com **chunks do seu PDF** em vez de documentos sintéticos.
"""

# ── Índice BM25 (lexical) ─────────────────────────────────────────────────────
# Tokeniza cada chunk em lista de palavras (tudo em minúsculo, só alfanumérico)

def tokenizar(texto):
    return re.findall(r"\w+", texto.lower())

corpus_tokenizado = [tokenizar(c["texto"]) for c in chunks]
indice_bm25 = BM25Okapi(corpus_tokenizado)

print(f"Índice BM25 criado com {len(chunks)} documentos.")

# ── Índice de Embeddings (semântico) ──────────────────────────────────────────
# Usamos o mesmo modelo multilingual da Atividade 3.
# Isso pode levar 1-3 min dependendo do tamanho do PDF.

print("Carregando modelo de embeddings...")
modelo_embed = SentenceTransformer("sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2")

print(f"Gerando embeddings para {len(chunks)} chunks...")
textos = [c["texto"] for c in chunks]
matriz_emb = modelo_embed.encode(
    textos,
    normalize_embeddings=True,   # norma = 1, produto interno vira cosine similarity
    show_progress_bar=True,
).astype("float32")

# Cria índice FAISS de produto interno (= cosine quando vetores normalizados)
dim = matriz_emb.shape[1]
indice_faiss = faiss.IndexFlatIP(dim)
indice_faiss.add(matriz_emb)

print(f"Índice FAISS criado: {dim} dimensões, {indice_faiss.ntotal} vetores.")

"""---
## ETAPA 4 — Retrieval: Buscar trechos relevantes

Implementamos as três funções de recuperação da Atividade 3, agora operando sobre os chunks do PDF.
"""

# ── Funções de Retrieval ──────────────────────────────────────────────────────

def recuperar_bm25(pergunta, k=3):
    """Busca léxica: pontua chunks por frequência de termos da pergunta."""
    scores = indice_bm25.get_scores(tokenizar(pergunta))
    idx = np.argsort(scores)[::-1][:k]
    return [{"id": chunks[i]["id"], "texto": chunks[i]["texto"], "score": float(scores[i])} for i in idx]


def recuperar_dense(pergunta, k=3):
    """Busca semântica: encontra chunks com significado similar à pergunta."""
    q = modelo_embed.encode([pergunta], normalize_embeddings=True).astype("float32")
    scores, idx = indice_faiss.search(q, k)
    # Quando k > total de chunks, FAISS preenche com índice -1.
    # Em Python, chunks[-1] retornaria o último chunk (errado!), então filtramos.
    return [
        {"id": chunks[i]["id"], "texto": chunks[i]["texto"], "score": float(scores[0][j])}
        for j, i in enumerate(idx[0])
        if i >= 0
    ]


def normalizar(v):
    """Normaliza um vetor para o intervalo [0, 1]."""
    v = np.array(v, dtype="float32")
    delta = float(v.max() - v.min())
    if delta < 1e-9:
        return np.zeros_like(v)
    return (v - v.min()) / delta


def recuperar_hibrido(pergunta, k=3, alpha=0.6):
    """
    Combina BM25 e semântico.
    alpha = peso do semântico (0 = só BM25, 1 = só semântico, 0.6 = padrão)
    """
    sb = normalizar(indice_bm25.get_scores(tokenizar(pergunta)))
    q = modelo_embed.encode([pergunta], normalize_embeddings=True).astype("float32")
    sd = normalizar(np.dot(matriz_emb, q[0]))
    score_final = alpha * sd + (1.0 - alpha) * sb
    idx = np.argsort(score_final)[::-1][:k]
    return [{"id": chunks[i]["id"], "texto": chunks[i]["texto"], "score": float(score_final[i])}
            for i in idx]


print("Funções de retrieval prontas!")

# ── Teste de Retrieval ────────────────────────────────────────────────────────
# Troque a pergunta por algo relacionado ao seu PDF!

PERGUNTA_TESTE = "qual e a metaheuristica usada nesse artigo"   # ← edite aqui
METODO        = "dense"                                  # "bm25", "dense" ou "hibrido"
K             = 3                                          # quantos trechos recuperar

if METODO == "bm25":
    resultados = recuperar_bm25(PERGUNTA_TESTE, k=K)
elif METODO == "dense":
    resultados = recuperar_dense(PERGUNTA_TESTE, k=K)
else:
    resultados = recuperar_hibrido(PERGUNTA_TESTE, k=K, alpha=0.6)

print(f"Pergunta : {PERGUNTA_TESTE}")
print(f"Método   : {METODO}")
print(f"k        : {K}")
print()
for r in resultados:
    print(f"[{r['id']}] Score: {r['score']:.4f}")
    print(textwrap.fill(r['texto'][:300], width=90))
    print("─" * 90)

"""### 🔎 Reflexão — Comparando os três métodos de retrieval

Execute a célula acima trocando `METODO` para `"bm25"`, `"dense"` e `"hibrido"`.  
Use a mesma pergunta e compare os resultados:

- Os chunks recuperados fazem sentido para a pergunta?
- Algum método trouxe chunks claramente melhores?
- O método `bm25` tende a favorecer chunks que contêm as **mesmas palavras** da pergunta.  
  O `dense` consegue encontrar chunks **semanticamente próximos** mesmo sem as mesmas palavras.  
  O `hibrido` tenta combinar o melhor dos dois.

---
## ETAPA 5 — Geração de Resposta com LLM

Agora montamos o pipeline RAG completo: recupera os chunks e passa para o LLM gerar uma resposta em linguagem natural.
"""

from openai import OpenAI

client = OpenAI(base_url='https://llm.liaufms.org/v1/gemma-3-12b-it', api_key='m71D5aqDATPQt_GV_3nmdO8nK8wB4Vb5PzV-d4bRGYc')
resp = client.chat.completions.create(
    model='google/gemma-3-12b-it',
    messages=[{'role': 'user', 'content': 'Hi'}],
)
print(resp.choices[0].message.content)

# ── Pipeline RAG completo ─────────────────────────────────────────────────────

def construir_prompt(pergunta, docs):
    """
    Monta o conteúdo da mensagem do usuário enviada ao LLM.
    O modelo deve responder APENAS com base no contexto fornecido.
    """
    contexto = "\n\n".join(
        [f"Trecho {i+1}:\n{d['texto']}" for i, d in enumerate(docs)]
    )
    return (
        "Responda em portugues usando apenas o contexto abaixo. "
        "Se nao houver informacao suficiente, diga: nao encontrado no contexto.\n\n"
        f"Contexto:\n{contexto}\n\n"
        f"Pergunta: {pergunta}"
    )


def responder_rag(pergunta, metodo="hibrido", k=3, alpha=0.6, max_tokens=512):
    """
    Função principal do RAG:
      1. Recupera os k chunks mais relevantes
      2. Monta o prompt com o contexto usando o chat template do Qwen2.5
      3. Gera a resposta com o LLM
    """
    # ── Passo 1: Recuperação ──
    if metodo == "bm25":
        docs = recuperar_bm25(pergunta, k=k)
    elif metodo == "dense":
        docs = recuperar_dense(pergunta, k=k)
    else:
        docs = recuperar_hibrido(pergunta, k=k, alpha=alpha)

    # ── Passo 2: Construção do prompt via chat template ──
    conteudo = construir_prompt(pergunta, docs)
    messages = [{"role": "user", "content": conteudo}]
    resp = client.chat.completions.create(
        model='google/gemma-3-12b-it',
        messages=messages,
    )


    return resp.choices[0].message.content, docs


print("Pipeline RAG pronto!")

# ── Teste do RAG ──────────────────────────────────────────────────────────────
# Faça várias perguntas sobre o seu PDF e observe as respostas!

PERGUNTA = "o que e a construção gulosa randomizada"   # ← edite aqui
METODO   = "hibrido"                                  # "bm25", "dense" ou "hibrido"

resposta, docs = responder_rag(PERGUNTA, metodo=METODO, k=10)

print(f"PERGUNTA: {PERGUNTA}")
print()
print("TRECHOS RECUPERADOS:")
for d in docs:
    print(f"  [{d['id']}] score={d['score']:.4f} | {d['texto'][:100]}...")
print()
print("RESPOSTA DO RAG:")
print(textwrap.fill(resposta, width=90))

# ── Comparar os três métodos para a mesma pergunta ────────────────────────────
# Isso mostra como a escolha do retrieval afeta a resposta final.

PERGUNTA_COMP = "quanto tempo demora para terminar o mestrado?"   # ← edite aqui

for metodo in ["bm25", "dense", "hibrido"]:
    resp, _ = responder_rag(PERGUNTA_COMP, metodo=metodo, k=3)
    print(f"[{metodo.upper()}]")
    print(textwrap.fill(resp, width=90))
    print()

"""### 🔎 Reflexão — Qualidade das respostas

1. As respostas foram coerentes com o conteúdo do PDF?
2. O modelo "inventou" alguma informação que não estava nos trechos?
3. Qual método de retrieval gerou as melhores respostas? Por quê?
4. O que acontece quando você aumenta `k` (mais trechos no contexto)?

> **Conceito:** quando o modelo ignora o contexto e inventa informações, isso se chama **alucinação**.  
> RAG reduz alucinações porque ancora a resposta nos trechos recuperados.

---
## ETAPA 6 — Bot Telegram

Nesta etapa você vai criar um **bot no Telegram** que responde perguntas sobre o seu PDF!

### Como criar o token do bot
1. Abra o Telegram e procure pelo usuário **@BotFather**
2. Digite `/newbot` e siga as instruções
3. Anote o **token** gerado (formato: `123456:ABC-DEFGhijklmnopqrstuvwxyz`)
4. Cole o token na variável `TOKEN` abaixo

> **Atenção:** nunca compartilhe seu token publicamente!  
> No Colab, use `userdata` (Secrets 🔑) para não expor o token no código.
"""

# ── Configure o token do bot (sem expor no código) ───────────────────────────
#
# OPÇÃO RECOMENDADA — Secrets do Colab (menu 🔑 na barra lateral):
#   1. Clique em 🔑 > "Adicionar novo secret"
#   2. Nome: TELEGRAM_TOKEN  |  Valor: seu token do @BotFather
#   3. Execute esta célula — o token nunca fica visível no notebook
#
# Isso evita vazar o token ao compartilhar o notebook com o professor.

try:
    from google.colab import userdata
    TOKEN = userdata.get("TELEGRAM_TOKEN")
    print("Token carregado dos Secrets do Colab.")
except Exception:
    # Fallback: pede pelo input interativo (não fica salvo no código)
    TOKEN = input("Cole aqui o token do @BotFather: ").strip()

if not TOKEN:
    raise ValueError("Token vazio. Configure o Secrets ou reinsira o token.")

print("Token configurado — pronto para iniciar o bot.")

# ── Bot do Telegram ───────────────────────────────────────────────────────────
# O bot fica "ouvindo" mensagens e responde com o RAG.
#
# Comandos disponíveis no chat:
#   /start          — mensagem de boas-vindas
#   /metodo bm25    — troca para busca lexical
#   /metodo dense   — troca para busca semântica
#   /metodo hibrido — troca para busca híbrida (padrão)
#   qualquer texto  — faz uma pergunta ao RAG
#
# Para PARAR o bot: clique em Interromper execução (■) no Colab.

import asyncio
import nest_asyncio
from telegram import Update
from telegram.ext import ApplicationBuilder, CommandHandler, MessageHandler, filters, ContextTypes

# Colab já tem um event loop rodando; nest_asyncio permite aninhar outro dentro dele.
# Sem isso, app.run_polling() lançaria "RuntimeError: This event loop is already running".
nest_asyncio.apply()

# ── Estado global do bot ──
# Cada usuário pode escolher seu próprio método de retrieval.
metodo_usuario = {}   # chat_id -> "bm25" | "dense" | "hibrido"


def sanitizar_md(texto):
    """Remove caracteres especiais do Markdown para não quebrar o parse do Telegram."""
    for c in ["*", "_", "`", "[", "]"]:
        texto = texto.replace(c, "")
    return texto


async def cmd_start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Responde ao comando /start com instruções de uso."""
    texto = (
        "Olá! Sou um bot RAG conectado a um PDF.\n\n"
        "Me faça qualquer pergunta sobre o documento!\n\n"
        "Comandos disponíveis:\n"
        "  /metodo bm25    — busca por palavras-chave\n"
        "  /metodo dense   — busca semântica\n"
        "  /metodo hibrido — combina os dois (padrão)\n"
    )
    await update.message.reply_text(texto)


async def cmd_metodo(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Troca o método de retrieval para o usuário que enviou o comando."""
    chat_id = update.effective_chat.id
    opcoes_validas = {"bm25", "dense", "hibrido"}

    if context.args and context.args[0].lower() in opcoes_validas:
        metodo_usuario[chat_id] = context.args[0].lower()
        await update.message.reply_text(f"Método trocado para: {metodo_usuario[chat_id]}")
    else:
        await update.message.reply_text(
            "Uso: /metodo <bm25|dense|hibrido>\n"
            f"Método atual: {metodo_usuario.get(chat_id, 'hibrido')}"
        )


async def handle_pergunta(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Recebe uma mensagem de texto e responde usando o RAG."""
    chat_id  = update.effective_chat.id
    pergunta = update.message.text
    metodo   = metodo_usuario.get(chat_id, "hibrido")

    await update.message.reply_text(f"Buscando com método '{metodo}'...")

    # Roda o RAG em thread separada para não bloquear o event loop do bot
    try:
        resposta, docs = await asyncio.to_thread(
            responder_rag, pergunta, metodo, 3, 0.6
        )
    except Exception as e:
        await update.message.reply_text(f"Erro ao processar: {e}")
        return

    # Monta a mensagem — sanitiza tudo para não quebrar o parse do Telegram
    linhas = [f"📄 *Resposta ({metodo}):*\n{sanitizar_md(resposta)}\n"]
    linhas.append("*Trechos recuperados:*")
    for d in docs:
        trecho = sanitizar_md(d["texto"][:200])
        linhas.append(f"• `{d['id']}` (score {d['score']:.3f}): {trecho}...")

    mensagem = "\n".join(linhas)

    # Telegram limita mensagens a 4096 caracteres
    if len(mensagem) > 4096:
        mensagem = mensagem[:4090] + "\n[...]"

    await update.message.reply_text(mensagem, parse_mode="Markdown")


# ── Inicializa e executa o bot ────────────────────────────────────────────────
print("Iniciando bot...")
print("Procure seu bot no Telegram e envie /start")
print("Para parar: clique no botão ■ (Interromper execução) no Colab")

app = ApplicationBuilder().token(TOKEN).build()
app.add_handler(CommandHandler("start", cmd_start))
app.add_handler(CommandHandler("metodo", cmd_metodo))
app.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, handle_pergunta))

# run_polling() (sem await) gerencia o event loop internamente.
# nest_asyncio.apply() acima garante que isso funciona dentro do Colab.
app.run_polling()

"""### 🔎 Reflexão — Bot Telegram

1. Envie pelo menos **5 perguntas diferentes** ao bot e anote as respostas.
2. Use `/metodo bm25` e `/metodo dense` para comparar os resultados no chat.
3. Você notou alguma diferença de velocidade entre os métodos? Por quê?
4. O bot conseguiu responder perguntas que **não usam as mesmas palavras** do PDF?

---
## Exercícios — Atividade Avaliativa

### A1 — Chunking e Indexação (0 a 10)

1. Execute as **três estratégias de chunking** e preencha a tabela de reflexão da Etapa 2.
2. Escolha a estratégia que você acha que produz **os melhores chunks** para o seu documento e justifique em uma célula Markdown.
3. Com essa estratégia escolhida, execute o pipeline completo (Etapas 3 a 5).

### A2 — Comparação de Retrieval (0 a 10)

1. Escreva **5 perguntas** sobre o conteúdo do seu PDF.
2. Para cada pergunta, rode os três métodos (`bm25`, `dense`, `hibrido`) e anote qual trouxe os chunks mais relevantes.
3. Crie uma tabela no notebook com: pergunta, melhor método, justificativa.

### AO — Atividade Optativa: melhoria do bot (0 a 10)
Substitui a menor nota entre A1 e A2 se for maior.

Implemente **uma** das melhorias abaixo no bot do Telegram:
- `/k <numero>` — permite ao usuário trocar o número de trechos recuperados
- `/alpha <valor>` — permite ao usuário ajustar o parâmetro alpha do híbrido
- Histórico de perguntas: o bot guarda as últimas 5 perguntas e responde `/historico`
"""

# ── Cálculo de notas (UFMS) ────────────────────────────────────────────────────
# Preencha suas notas e frequência abaixo.

AVALIACAO = {
    "A1": 0.0,          # 0 a 10 — Chunking e Indexação
    "A2": 0.0,          # 0 a 10 — Comparação de Retrieval
    "AO": -1.0,         # 0 a 10 se fez a optativa; -1 se não fez
    "frequencia": 0.0,  # percentual de presença (0 a 100)
}

A1   = float(AVALIACAO["A1"])
A2   = float(AVALIACAO["A2"])
AO   = float(AVALIACAO["AO"])
freq = float(AVALIACAO["frequencia"])

notas = [A1, A2]
if AO >= 0:
    idx_menor = int(np.argmin(notas))
    if AO > notas[idx_menor]:
        notas[idx_menor] = AO

ma       = round(float(np.mean(notas)), 1)
aprovado = (freq >= 75.0) and (ma >= 6.0)

print("═" * 40)
print("RELATÓRIO UFMS — ATIVIDADE 4")
print("═" * 40)
print(f"A1 (Chunking)          : {A1:.1f}")
print(f"A2 (Retrieval)         : {A2:.1f}")
if AO >= 0:
    print(f"AO (Optativa)          : {AO:.1f}")
print(f"Média Aritmética       : {ma:.1f}")
print(f"Frequência             : {freq:.1f}%")
print("─" * 40)
print(f"Situação               : {'APROVADO ✓' if aprovado else 'REPROVADO ✗'}")
print("═" * 40)

# Célula temporária de validação local
texto_markdown = """
Regulamento do curso de exemplo.

O documento descreve critérios de avaliação, frequência mínima de 75 por cento
para aprovação e a necessidade de média aritmética maior ou igual a 6.0.

Também explica que recuperação híbrida combina busca lexical e semântica.
""".strip()

CAMINHO_PDF = "documento_teste.pdf"
print("Contexto de teste definido.")